platform :ios, '9.0'
use_frameworks!

target "Babble" do
	pod 'Firebase', '>= 2.5.0'
	pod 'Firebase/Auth'
	pod 'Firebase/Database'
	pod 'Firebase/Storage'
	pod 'FirebaseUI', '~> 0.4'
	pod 'Kingfisher', '~> 2.4'
end